version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:19.3.0

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test -- --watchAll=false

workflows:
  version: 2
  test:
    jobs:
      - test